version: '3'
services:
  node1:
    restart: always
    build: ./auth/
    ports:
      - 3000:3000
    volumes:
      - ./:/code
    depends_on:
      - mongo
  node2:
    restart: always
    build: ./crud/
    ports:
      - 4000:4000
    volumes:
      - ./:/code
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: